### ISSUE TITLE
프로젝트 포크하고싶은데, 라이선스를 여쭙고 싶습니다.

### ISSUE THREAD

**Issue by GG-O-BP** [ChoiJY/2016-2017_m2soft#6]
제가 라이선스가 명시되지 않은 프로젝트는 사용권 및 수정권 저작권 등을 공유할 수 없는 것으로 알고있습니다.

해당 프로젝트가 어떤 라이선스를 따르고있는지 확인 부탁드립니다.

**Comment by GG-O-BP** [comment]
제가 한자입력관련해서 조금 애를 먹었었는데, 이부분에 대한 개선점을 업데이트하고 싶었습니다.

**Comment by ChoiJY** [comment]
안녕하세요. 이 프로젝트 라이센스는 사용하고 있는 오픈소스 라이브러리들의 라이센스와 동일한 **MIT license**입니다. 

개선점이 있으시면 PR 요청 주시거나, 혹은 자체적으로 fork하셔서 사용하셔도 무방합니다.

**Comment by GG-O-BP** [comment]
확인감사합니다.
한자입력기능이 한자의 소스가 굉장히 길어서 다소 불편하여 해당 프로젝트에 올리지는 않고 따로 포크했습니다.
덕분에 잘 쓰고있습니다. 라이선스는 MIT로 올려놓겠습니다. 감사합니다.
